### ISSUE TITLE
求调试qq思路，比如您做这个红包是怎么分析的，光看源码感觉费劲呀，根本弄不出所以然

### ISSUE THREAD

**Issue by qssq** [xfunforx/XglyphController#1]
求您了。我折腾好几天了。。硬是不知道怎么搞才好

**Comment by xfunforx** [comment]
看什么源码？？

**Comment by qssq** [comment]
逆向qq的源码呀

**Comment by qssq** [comment]
光有解开源码的工具和xp的一些知识是不是不够呢？比如要掌握动态调试才行？

**Comment by xfunforx** [comment]
你说的太高级了。我没玩过动态调试。。

**Comment by qssq** [comment]
好吧，就是 这个东西不需要调试qq吗  就是把qq跑起来 然后 断点调试，直接逆向源码分析源码 然后hook一些类 然后反复的开关机？ 那你们太牛了，这种精神我佩服

**Comment by xfunforx** [comment]
因为 不会调试啊， 你会调试肯定可以用更好的方法了。我就是用了笨的方法。。

**Comment by qssq** [comment]
厉害啊，可以加个好友嘛

**Comment by xfunforx** [comment]
3133282258

**Comment by qssq** [comment]
--禁止查找  我的694886526
